import type { Metadata } from "next";
import { pretendard } from "@/fonts";
import { ThemeProvider } from "@/providers/ThemeProvider";
import "./globals.css";
import ToastProvider from "@/providers/ToastProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className={pretendard.className} suppressHydrationWarning>
      <body className={`antialiased`}>
        <ToastProvider />
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
